name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.18
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Build Micro
      run: make micro

    - name: Build Broker - Nats
      run: make
      working-directory: plugins/broker/nats

    - name: Build Cache - Redis
      run: make
      working-directory: plugins/cache/redis
